# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    """
    Class for main window.
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 300))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(170, 40, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_integer = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_integer.setGeometry(QtCore.QRect(150, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_integer.setFont(font)
        self.label_integer.setObjectName("label_integer")
        self.label_modulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_modulo.setGeometry(QtCore.QRect(150, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_modulo.setFont(font)
        self.label_modulo.setObjectName("label_modulo")
        self.input_integer = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_integer.setGeometry(QtCore.QRect(260, 130, 161, 22))
        self.input_integer.setObjectName("input_integer")
        self.input_modulo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_modulo.setGeometry(QtCore.QRect(260, 200, 161, 22))
        self.input_modulo.setObjectName("input_modulo")
        self.label_answer = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_answer.setGeometry(QtCore.QRect(90, 300, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_answer.setFont(font)
        self.label_answer.setText("")
        self.label_answer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_answer.setObjectName("label_answer")
        self.button_help = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_help.setGeometry(QtCore.QRect(500, 320, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.button_help.setFont(font)
        self.button_help.setObjectName("button_help")
        self.button_calculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_calculate.setGeometry(QtCore.QRect(240, 260, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.button_calculate.setFont(font)
        self.button_calculate.setObjectName("button_calculate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Modular Inverse Calculator"))
        self.label_title.setText(_translate("MainWindow", "Modular Inverse Calculator"))
        self.label_integer.setText(_translate("MainWindow", "Integer"))
        self.label_modulo.setText(_translate("MainWindow", "Modulus"))
        self.button_help.setText(_translate("MainWindow", "Help!"))
        self.button_calculate.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
